# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import user_pb2 as user__pb2


class UserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getUsers = channel.unary_unary(
        '/user.grpc.User/getUsers',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=user__pb2.UsersResponse.FromString,
        )
    self.createUser = channel.unary_unary(
        '/user.grpc.User/createUser',
        request_serializer=user__pb2.createUserRequest.SerializeToString,
        response_deserializer=user__pb2.createUserResponse.FromString,
        )


class UserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getUsers': grpc.unary_unary_rpc_method_handler(
          servicer.getUsers,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=user__pb2.UsersResponse.SerializeToString,
      ),
      'createUser': grpc.unary_unary_rpc_method_handler(
          servicer.createUser,
          request_deserializer=user__pb2.createUserRequest.FromString,
          response_serializer=user__pb2.createUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'user.grpc.User', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
